import Head from 'next/head';
import React, { useEffect } from 'react';
import NextLink from "next/link";
import { TextField, Typography } from '@mui/material';
import { Button } from '@mui/material';
import { useSelector, useDispatch } from 'react-redux';
import { change, register } from '../../store/actions/register.action';
import { useRouter } from 'next/router';

export default function RegisterScreen() {
    const router = useRouter();
    const dispatch = useDispatch();
    const { user, success, error } = useSelector(state => state.registerReducer);

    useEffect(() => {
        if ((success)) {
            router.push('/products')
        }
    }, [success]);

    const registrar = (user) => {
        dispatch(register(user))
    };

    return (
        <React.Fragment>
            <Head>
                <title>Registro de usuário - CRM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='d-flex bg-white min-vh-100'>
                <div className='container mt-5'>
                    <div className='row justify-content-center'>
                        <div className='col-md-4'>
                            <div className='form-group text-center'>
                                <p>CRM</p>
                                <Typography variant="h6" component="h1">
                                    Plataform de revenda
                                </Typography>
                            </div>

                            <TextField
                                label="Nome"
                                placeholder='Fulano de tal'
                                type="text"
                                margin='normal'
                                fullWidth
                                value={user.name}
                                onChange={text => {
                                    dispatch(change({ name: text.target.value }))
                                }}
                            />

                            <div className='text-danger'>
                                {error.name &&
                                    <strong>{error.name[0]}</strong>
                                }
                            </div>

                            <TextField
                                label="Email"
                                placeholder='user@mail.com'
                                type="email"
                                margin='normal'
                                autoComplete='email'
                                fullWidth
                                value={user.email}
                                onChange={text => {
                                    dispatch(change({ email: text.target.value }))
                                }}
                            />


                            <div className='text-danger'>
                                {error.email &&
                                    <strong>{error.email[0]}</strong>
                                }
                            </div>

                            <TextField
                                label="Senha"
                                type="password"
                                margin='normal'
                                fullWidth
                                value={user.password}
                                onChange={text => {
                                    dispatch(change({ password: text.target.value }))
                                }}
                            />

                            <div className='text-danger'>
                                {error.password &&
                                    <strong>{error.password[0]}</strong>
                                }
                            </div>

                            <div>
                                <NextLink href="/login">Já tenho conta</NextLink>
                            </div>

                            <Button
                                variant="contained"
                                color="primary"
                                fullWidth
                                size="large"
                                className='mt-4 mb-4'
                                onClick={() => {
                                    registrar(user)
                                }}
                            >
                                Cadastrar
                            </Button>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    )
}
