import Head from 'next/head';
import React from 'react';
import Header from '../../layout/Header'

export default function ProductsScreen() {
    return (
        <React.Fragment>
            <Head>
                <title>Produtos - Site CRM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <div className='container-fluid'>
                produtos
            </div>
        </React.Fragment>
    )
}
