import Head from 'next/head'
import React, { useEffect } from 'react'
import NextLink from "next/link";

import { TextField, Typography } from '@mui/material'
import { Button } from '@mui/material'
import { useSelector, useDispatch } from 'react-redux';
import { change, login } from '../../store/actions/auth.action';
import { useRouter } from 'next/router';

export default function AuthScreen() {
    const router = useRouter();
    const dispatch = useDispatch();
    const { credentials, success } = useSelector(state => state.authReducer);

    useEffect(() => {
        if ((success)) {
            router.push('/vehicles')
        }
    }, [success])

    return (
        <React.Fragment>
            <Head>
                <title>CRM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='d-flex bg-white min-vh-100'>
                <div className='container mt-5'>
                    <div className='row justify-content-center'>
                        <div className='col-md-4'>
                            <div className='form-group text-center'>
                                <p>CRM</p>
                                <Typography variant="h6" component="h1">
                                    Plataform de revenda
                                </Typography>
                            </div>

                            <TextField
                                label="Email"
                                placeholder='user@mail.com'
                                type="email"
                                margin='normal'
                                autoComplete='email'
                                fullWidth
                                value={credentials.email}
                                onChange={text => {
                                    dispatch(change({ email: text.target.value }))
                                }}
                            />

                            <TextField
                                label="Senha"
                                type="password"
                                margin='normal'
                                fullWidth
                                value={credentials.password}
                                onChange={text => {
                                    dispatch(change({ password: text.target.value }))
                                }}
                            />

                            <div>
                                <NextLink href="/register">Criar conta</NextLink>
                            </div>

                            <Button
                                variant="contained"
                                color="primary"
                                fullWidth
                                size="large"
                                className='mt-4 mb-4'
                                onClick={() => {
                                    dispatch(login(credentials))
                                }}
                            >
                                Login
                            </Button>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    )
}
