import Head from 'next/head';
import React from 'react';
import Header from '../../layout/Header'

export default function VehiclesScreen() {
    return (
        <React.Fragment>
            <Head>
                <title>Veiculos - Site CRM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header title="Vehicles" />

            <div className='container-fluid'>
                Veiculos
            </div>
        </React.Fragment>
    )
}
